export default function About() {
   return (
      <>
         <h2>Sobre Mim</h2>
         <p>Esse é minha rota para Sobre mim</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
      </>
   )
}