export default function Education() {
   return (
      <>
         <h2>Formação e Certificados</h2>
         <p>Esse é minha rota para Formação e certificados</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
         <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Unde enim quia accusamus reiciendis alias, tenetur tempora voluptate dolores quis repudiandae debitis reprehenderit, delectus odit odio et atque perspiciatis cupiditate officia?</p>
      </>
   )
}